baseurl: https://butecotecnologico.com.br/
title: Buteco Tecnológico
languageCode: pt-BR
languageName: Portuguese
defaultContentLanguage: pt
enableInlineShortcodes: true
summarylength: 10
enableEmoji: true
paginate: 25
theme: iara
disqusShortname: butecoopensource
googleAnalytics: UA-55693832-1
disableKinds:
  - pages

taxonomies:
  category: categories
  series: series
  tag: tags
  podcast: podcasts
  author: authors

permalinks:
  posts: /:slug/
  podcast: /podcast/:slug/
  categories: /categorias/:slug/
  tags: /tags/:slug/
  authors: /autores/:slug/

outputs:
  home:
    - HTML
    - RSS
  page:
    - HTML
  section:
    - HTML
  taxonomy:
    - HTML
  term:
    - HTML

outputFormats:
  sharing-v1:
    path: v1
    baseName: sharing
    isPlainText: true
    mediaType: application/json
    protocol: https://
    notAlternative: true
  posts-v1:
    path: v1
    baseName: posts
    isPlainText: true
    mediaType: application/json
    protocol: https://
    notAlternative: true
  authors-v1:
    path: v1
    baseName: authors
    isPlainText: true
    mediaType: application/json
    protocol: https://
    notAlternative: true
  tags-v1:
    path: v1
    baseName: tags
    isPlainText: true
    mediaType: application/json
    protocol: https://
    notAlternative: true
  categories-v1:
    path: v1
    baseName: categories
    isPlainText: true
    mediaType: application/json
    protocol: https://
    notAlternative: true

params:
  mainSections:
    - posts
    - podcast
    - wordpress
  title: Buteco Tecnológico
  description: Um blog feito por, e para pessoas que gostam de compartilhar suas experiências com tecnologia, linux e software livre.
  images:
    - /logos/capybara_400_bg.png
    - /logos/capybara_400.png
  logo: /logos/capybara_64.png
  copyright: Buteco Tecnológico
  builtWith: false

  # dateFormat: "Jan 2, 2006"
  dateFormat: "02/01/2006"

  organization:
    name: Buteco Tecnológico
    url: https://butecotecnologico.com.br/
    logo: /logos/capybara_400.png
    sameas:
      - https://www.linkedin.com/company/butecotecnologico
      - https://twitter.com/butecotech
      - https://www.facebook.com/buteco.tech
      - https://www.youtube.com/c/ButecoTech
      - https://www.instagram.com/buteco.tech/

  #
  # Sidebar
  #
  # Sidebar is hidden on small devices (< 576px)
  sidebar:
    show: true

    categories:
      show: true   # Show categories in sidebar
      count: true  # Show article count in category
    tags:
      show: false   # Show tags in sidebar
      count: true  # Show article count in tag
    #
    # Feature articles
    #
    featured:
      index: true  # Show index number
      item:
        - path: posts/2020-06-16-de-que-sao-feitos-containers-linux.md
        - path: posts/2020-08-13-kubernetes-explicado.md
        - path: posts/2020-05-15-usando-aws-s3-em-python.md
        - path: posts/2020-04-24-livros-gratuitos.md
        - path: posts/2020-05-20-ubuntu-20-04.md

  license:
    name: CC BY-SA 4.0
    url: 'https://creativecommons.org/licenses/by-sa/4.0'

  search:
    enabled: true
    provider: google
    google:
      id: 006529162228150198964:ypsteas3iuv

  addthis:
    pubid: ra-56269d97a8b5a42b

  ads:
    google:
      id: ca-pub-6625957038449899

  social:
    - icon: fab fa-telegram-plane
      title: Telegram
      url: https://t.me/butecotecnologico
    - icon: fab fa-discord
      title: Discord
      url: https://discord.gg/eX2jAvw
    - icon: fab fa-twitter
      title: Twitter
      url: https://twitter.com/butecotech
    - icon: fab fa-linkedin-in
      title: Linkedin
      url: https://www.linkedin.com/company/butecotecnologico
    - icon: fab fa-facebook-f
      title: Facebook
      url: https://www.facebook.com/buteco.tech
    - icon: fab fa-youtube
      title: YouTube
      url: https://www.youtube.com/c/ButecoTech
    - icon: fab fa-instagram
      title: Instagram
      url: https://www.instagram.com/buteco.tech/
    # - icon: fab fa-github-alt
    #   title: GitHub
    #   url: https://github.com/ButecoOpenSource
    - icon: fas fa-rss
      title: Feed RSS
      url: /feed-rss/
menu:
  main:
    - name: Início
      weight: 1
      url: /
      pre: <span class="mr-1"><i class="fas fa-home"></i></span>
    - name: Podcast
      weight: 2
      url: /podcast/
      pre: <span class="mr-1"><i class="fas fa-microphone-alt"></i></span>
    - name: Anuncie
      weight: 3
      url: /anuncie-conosco/
      pre: <span class="mr-1"><i class="fas fa-bullhorn"></i></span>
    - name: Colabore
      weight: 4
      url: /contribua-com-nosso-blog/
      pre: <span class="mr-1"><i class="far fa-heart"></i></span>
    - name: Contato
      weight: 5
      url: /contato/
      pre: <span class="mr-1"><i class="fas fa-phone"></i></span>
  carousel:
    - name: Cloud Computing
      weight: 1
      url: /categorias/cloud-computing/
    - name: Embarcados
      weight: 2
      url: /categorias/embarcados/
    - name: Data Science
      weight: 3
      url: /categorias/data-science/
    - name: IA
      weight: 3
      url: /categorias/inteligencia-artificial/
    - name: Distros
      weight: 4
      url: /categorias/distros/
    - name: Segurança
      weight: 5
      url: /categorias/seguranca/
    - name: Privacidade
      weight: 6
      url: /categorias/privacidade/
    - name: Reviews
      weight: 7
      url: /categorias/reviews/
  terms:
    - name: Termos de Uso
      weight: 1
      url: /termos-de-uso/
    - name: Privacidade
      weight: 2
      url: /politica-de-privacidade/
  footer1:
    - name: Cloud Computing
      weight: 1
      url: /categorias/cloud-computing/
      pre: <b>
      post: </b>
    - name: Kubernetes
      weight: 2
      url: /tags/kubernetes/
    - name: Docker
      weight: 3
      url: /tags/docker/
    - name: Virtualização
      weight: 4
      url: /tags/virtualizacao/
    - name: AWS
      weight: 5
      url: /tags/aws/
  footer2:
    - name: Embarcados
      weight: 1
      url: /categorias/embarcados/
      pre: <b>
      post: </b>
    - name: Raspberry Pi
      weight: 2
      url: /tags/raspberry-pi/
    - name: ARM
      weight: 3
      url: /tags/arm/
    - name: Arduino
      weight: 4
      url: /tags/arduino/
    - name: Internet das Coisas
      weight: 5
      url: /tags/iot/
    - name: DIY
      weight: 6
      url: /tags/diy/
  footer3:
    - name: Desenvolvimento
      weight: 1
      url: /categorias/desenvolvimento/
      pre: <b>
      post: </b>
    - name: Python
      weight: 2
      url: /tags/python/
    - name: C/C++
      weight: 3
      url: /tags/cpp/
    - name: PHP
      weight: 4
      url: /tags/php/
    - name: Node.JS
      weight: 5
      url: /tags/node-js/
    - name: Lua
      weight: 6
      url: /tags/lua/
  footer4:
    - name: Distros
      weight: 1
      url: /categorias/distros/
      pre: <b>
      post: </b>
    - name: Linux
      weight: 2
      url: /tags/linux/
    - name: Ubuntu
      weight: 3
      url: /tags/ubuntu/
    - name: Fedora
      weight: 4
      url: /tags/fedora/
    - name: CentOS
      weight: 5
      url: /tags/centos/
    - name: openSUSE
      weight: 6
      url: /tags/opensuse/
    - name: BSD
      weight: 7
      url: /tags/bsd/
  footer5:
    - name: Podcast
      weight: 1
      url: /podcast/
      pre: <b>
      post: </b><span class="badge badge-success">Novo</span>
    - name: Contribua com o blog
      weight: 2
      url: /contribua-com-nosso-blog/
      post: <i class="far fa-heart text-danger"></i>
    - name: Anuncie conosco
      weight: 3
      url: /anuncie-conosco/
    - name: Categorias
      weight: 4
      url: /categorias/
    - name: Autores
      weight: 5
      url: /autores/
    # - name: Tags
    #   weight: 6
    #   url: /tags/
  footer6:
    - name: Contato
      weight: 1
      url: /contato/
      pre: <b>
      post: </b>
    - name: Sobre nós
      weight: 2
      url: /sobre/
    - name: Equipe
      weight: 3
    - name: Feed RSS
      weight: 4
      url: /feed-rss/
      url: /equipe/
    - name: Estatísticas
      weight: 5
      url: https://estatisticas.buteco.me/

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ''
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: false
    style: github
    tabWidth: 4
